### PR TITLE
This fixes dpkg-buildpackage

### PR DESCRIPTION
**Pull request by kkroo**
- Release name is sipauthserve, no public suffix. That was breaking things.
- Disabled dh_link since that was doing funny things like deleting the
- binary before packaging it

### CODE REVIEW

**Comment by yosemitebandit** [comment]
why does the public suffix break stuff?  Just curious.. I believe that suffix is also on `smqueue`, fyi

**Comment by kkroo** [comment]
The package name `sipauthserve` is hardcoded in a few different locations so that when we run `dpkg-buildpackage`, some of the files end up being packaged in a directory named `sipauthserve` while the rest show up in `sipauthserve-public` so when it creates the `.deb` we aren't collecting everything that was built. 

I'm going to have to do the same thing in `smqueue` which is why it is breaking. Maybe in fixing that one, I'll find what value I need to change to make it work with `-public`. Keeping this open until then.

**Comment by kkroo** [comment]
Hopefully this should do the trick.. needs to be tested on fresh instance still

**Comment by kkroo** [comment]
PTAL. Works on fresh instance

**Comment by shaddi** [comment]
How are you installing this? This package is missing a `libosip2-4` dependency on my box...

**Comment by shaddi** [comment]
I'm getting this error when I try to run `dpkg-buildpackage` from a fresh repo:

```
vagrant@vagrant-ubuntu-trusty-32:~/subscriberRegistry⟫ dpkg-buildpackage 
dpkg-buildpackage: source package sipauthserve-public
dpkg-buildpackage: source version 5.0
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Range Packager <buildmeister@rangenetworks.com>
dpkg-buildpackage: host architecture i386
 dpkg-source --before-build subscriberRegistry
 fakeroot debian/rules clean
dh_testdir
# Add here commands to configure the package.
touch configure-stamp
dh_testdir
dh_testroot
rm -f build-arch-stamp build-indep-stamp configure-stamp
# Add here commands to clean up after the build process.
/usr/bin/make clean
make[1]: Entering directory `/home/vagrant/subscriberRegistry'
make[1]: *** No rule to make target `clean'.  Stop.
make[1]: Leaving directory `/home/vagrant/subscriberRegistry'
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
```

Any ideas?

**Comment by shaddi** [comment]
Ok, e02f121 fixes that last bit (it wasn't running autoconf and configure, hence no Makefiles -- very confused how you got this to build!). The example sql is not building still though.

**Comment by kkroo** [comment]
For the `libosip2` dependency, I fetched it from `trusty/main`.

Well it looks like I ran it on a fresh VM alright, but it wasnt a fresh repo so these files may have already been made. Thanks for the autogen fix.

The issue about the sql file I remember, and was thankful I didn't encounter it last night. Know why now.. But the problem is that it uses the `sipauthserve` binary to generate the sql file, and I can't remember what the original problem was. Probably bad order of calls..

 `git clean`ing and retrying this.

**Comment by shaddi** [comment]
Sweet, if we can get the sql to build right I think we're good on this one finally!

**Comment by kkroo** [comment]
cool so this seems to mysteriously work with #6 

```
cd subscriberRegistry/
git clean -fx
cd ../client
vagrant destroy
vagrant up
fab dev package_sipauthserve update
```

Works mysteriously for me without changing a darn thing.

**Comment by shaddi** [comment]
So a clean build works, does it work when you run `fab dev package_sipauthserve update` again?

**Comment by kkroo** [comment]
I'm running the whole darn `fab dev package update` as we speak so we'll see the outcome of that

**Comment by kkroo** [comment]
My theory is that it was acting funny because of the package renaming that was going on. If you installed it as `sipauthserve` and then tried as `sipauthserve-public` it wouldn't copy over the sql file?

**Comment by shaddi** [comment]
This builds, installs, and runs fine. LGTM.

**Pull request merged**
