### PR TITLE
Adds support for port lookup.

### PR DESCRIPTION
**Pull request by kheimerl**
Adds support for reading ports from subscriber registry

### CODE REVIEW

**Comment by yosemitebandit** [comment]
openbts-python already supports looking up the OpenBTS port through NM, or is this something different?

**Comment by yosemitebandit** [comment]
https://github.com/endaga/openbts-python/blob/master/integration_tests.py#L151  does this work / give you what you want?

**Comment by kheimerl** [comment]
This is for smq.

**Comment by yosemitebandit** [comment]
which is for smqueue?  this PR..?

**Comment by kheimerl** [comment]
SMQ uses SR as a library. It needs this functionality to look up user ports when routing comms.

**Comment by yosemitebandit** [comment]
ah, I see

**Comment by shaddi** [comment]
lgtm

**Pull request merged**
